<a href="https://colab.research.google.com/github/anhdt061091/data-science/blob/master/Assignment1_Duong_Tuan_Anh_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programming Assignment 1: Text Classification

In this programming assignment, you will build a text classifier that can classify scientific articles into categories using their abstract.

You are free to use any machine learning algorithm. However, you have to do this assignment and report results on test data using notebook (Google Colab or Jupyter Notebook).

## Submission

**Due date: 23:59 September 8, 2020 (Tuesday)**. It is the hard deadline. I will not grade for late submissions.

What to submit:
- A notebook file (.ibynb) that contains your solution for the assignment. Inside the notebook, you will write code to build the classification model and report the results on test data (accuracy, precision, recall, f1 scores).
- Name your notebook as `Assignment1_<Yourname>_<StudentID>.ibynb`
- Write your name on the notebook

How to submit:
- Attach your notebook file and send to my email gv.minhpqn@fsb.edu.vn with the email subject "Assignment 1 - \<Yourname\>"


## Dataset

We sample data from [arXiv dataset](https://www.kaggle.com/Cornell-University/arxiv) and split the data into train/test sets. There are 10 categories in our data.

We will download the data using the following commands

In [ ]:
!rm -f train.csv test.csv
!wget https://raw.githubusercontent.com/minhpqn/NLP-Notes/master/data/arxiv/train.csv
!wget https://raw.githubusercontent.com/minhpqn/NLP-Notes/master/data/arxiv/test.csv

--2020-09-05 06:23:13--  https://raw.githubusercontent.com/minhpqn/NLP-Notes/master/data/arxiv/train.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10400749 (9.9M) [text/plain]
Saving to: ‘train.csv’

train.csv           100%[===================>]   9.92M  18.4MB/s    in 0.5s    

2020-09-05 06:23:14 (18.4 MB/s) - ‘train.csv’ saved [10400749/10400749]

--2020-09-05 06:23:14--  https://raw.githubusercontent.com/minhpqn/NLP-Notes/master/data/arxiv/test.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1133794 (1.1M) [text/plain]
Saving

## Reading Data

We can use [pandas](https://pandas.pydata.org/) module to read data into DataFrame objects.

In [ ]:
import pandas as pd

train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

Let's see some rows in the data frame `train_df`.

In [ ]:
train_df.head()

id  ...  category
0  1901.05003  ...  quant-ph
1  1903.08905  ...        cs
2  1907.11533  ...     q-bio
3  1711.07582  ...      stat
4  1910.05833  ...  quant-ph

[5 rows x 4 columns]

## Assignment Assement

- Loading & preprocessing data: 20 points
- Training model: 40 points
- Evaluation on test data: 40 points


# New Section

In [ ]:
train_df.describe()

id  ...  category
count         9000  ...      9000
unique        9000  ...        10
top     1803.03862  ...  cond-mat
freq             1  ...       900

[4 rows x 4 columns]

In [ ]:
test_df.head(10)

id  ...  category
0  2004.12573  ...      eess
1  1908.01621  ...    hep-ph
2  1906.10356  ...      eess
3  1905.10272  ...     q-bio
4  1910.01033  ...  cond-mat
5  1901.11248  ...  cond-mat
6  1704.03005  ...      stat
7  2008.09726  ...  quant-ph
8  1911.01127  ...    hep-th
9  1906.02822  ...      stat

[10 rows x 4 columns]

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        9000 non-null   object
 1   title     9000 non-null   object
 2   abstract  9000 non-null   object
 3   category  9000 non-null   object
dtypes: object(4)
memory usage: 281.4+ KB


In [ ]:
dummy_variable_1 = pd.get_dummies(train_df["category"])

In [ ]:
print(dummy_variable_1)

      astro-ph  cond-mat  cs  eess  hep-ph  hep-th  math  q-bio  quant-ph  stat
0            0         0   0     0       0       0     0      0         1     0
1            0         0   1     0       0       0     0      0         0     0
2            0         0   0     0       0       0     0      1         0     0
3            0         0   0     0       0       0     0      0         0     1
4            0         0   0     0       0       0     0      0         1     0
...        ...       ...  ..   ...     ...     ...   ...    ...       ...   ...
8995         0         0   0     0       0       0     0      0         1     0
8996         0         0   0     0       0       1     0      0         0     0
8997         0         0   0     0       0       1     0      0         0     0
8998         0         0   0     0       0       0     0      0         1     0
8999         0         0   0     0       0       0     0      0         0     1

[9000 rows x 10 columns]


In [ ]:
dummy_variable_1.head()

astro-ph  cond-mat  cs  eess  hep-ph  hep-th  math  q-bio  quant-ph  stat
0         0         0   0     0       0       0     0      0         1     0
1         0         0   1     0       0       0     0      0         0     0
2         0         0   0     0       0       0     0      1         0     0
3         0         0   0     0       0       0     0      0         0     1
4         0         0   0     0       0       0     0      0         1     0

In [ ]:
train_df = pd.concat([train_df, dummy_variable_1], axis=1)

In [ ]:
train_df.drop("category", axis = 1, inplace=True)

In [ ]:
train_df.head()

id  ... stat
0  1901.05003  ...    0
1  1903.08905  ...    0
2  1907.11533  ...    0
3  1711.07582  ...    1
4  1910.05833  ...    0

[5 rows x 13 columns]

In [ ]:
test_df.head()

id  ...  category
0  2004.12573  ...      eess
1  1908.01621  ...    hep-ph
2  1906.10356  ...      eess
3  1905.10272  ...     q-bio
4  1910.01033  ...  cond-mat

[5 rows x 4 columns]

In [ ]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from scipy.sparse import hstack

In [ ]:
class_names =['astro-ph', 'cond-mat','cs','eess','hep-ph','hep-th','math','q-bio','quant-ph','stat' ]

In [ ]:
train_text = train_df['abstract']
test_text = test_df['abstract']
all_text = pd.concat([train_text, test_text])

In [ ]:
word_vectorizer = TfidfVectorizer(
    sublinear_tf=True,
    strip_accents='unicode',
    analyzer='word',
    token_pattern=r'\w{1,}',
    stop_words='english',
    ngram_range=(1, 1),
    max_features=10000)

In [ ]:
word_vectorizer.fit(all_text)
train_word_features = word_vectorizer.transform(train_text)
test_word_features = word_vectorizer.transform(test_text)

In [ ]:
char_vectorizer = TfidfVectorizer(
    sublinear_tf=True,
    strip_accents='unicode',
    analyzer='char',
    stop_words='english',
    ngram_range=(2, 6),
    max_features=50000)

In [ ]:
char_vectorizer.fit(all_text)
train_char_features = char_vectorizer.transform(train_text)
test_char_features = char_vectorizer.transform(test_text)

/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:520: UserWarning: The parameter 'stop_words' will not be used since 'analyzer' != 'word'
  warnings.warn("The parameter 'stop_words' will not be used"


In [ ]:
train_features = hstack([train_char_features, train_word_features])
test_features = hstack([test_char_features, test_word_features])

In [ ]:
scores = []
submission = pd.DataFrame.from_dict({'id': test_df['id']})
for class_name in class_names:
    train_target = train_df[class_name]
    classifier = LogisticRegression(C=0.1, solver='sag')

    cv_score = np.mean(cross_val_score(classifier, train_features, train_target, cv=3, scoring='roc_auc'))
    scores.append(cv_score)
    print('CV score for class {} is {}'.format(class_name, cv_score))

    classifier.fit(train_features, train_target)
    submission[class_name] = classifier.predict_proba(test_features)[:, 1]

CV score for class astro-ph is 0.9955028806584362
CV score for class cond-mat is 0.9845930041152263
CV score for class cs is 0.9557444444444445
CV score for class eess is 0.9772740740740741
CV score for class hep-ph is 0.9954325102880658
CV score for class hep-th is 0.992025514403292
CV score for class math is 0.9818127572016461
CV score for class q-bio is 0.9814131687242797
CV score for class quant-ph is 0.9902802469135802
CV score for class stat is 0.9832440329218106


In [ ]:
print('Total CV score is {}'.format(np.mean(scores)))

Total CV score is 0.9837322633744854


In [ ]:
submission.head()

id  astro-ph  cond-mat  ...     q-bio  quant-ph      stat
0  2004.12573  0.040221  0.033025  ...  0.081140  0.051045  0.318164
1  1908.01621  0.059734  0.072590  ...  0.076509  0.052788  0.085800
2  1906.10356  0.089927  0.047372  ...  0.076573  0.070610  0.082144
3  1905.10272  0.081007  0.080256  ...  0.242830  0.066492  0.071437
4  1910.01033  0.068740  0.145125  ...  0.130357  0.086347  0.075114

[5 rows x 11 columns]

In [ ]:
submission1 = submission.drop (['id'], axis = 1)

In [ ]:
i = 0
y = np.zeros((1000,10))
for i in range(1000):
  x = submission1.iloc[i]
  y[i] = np.zeros(x.shape)
  y[i][np.argmax(x)] = 1
  i = i + 1 
print(y)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
submission2 = pd.DataFrame(data=y, columns=['astro-ph','cond-mat','cs','eess','hep-ph','hep-th','math','q-bio','quant-ph','stat'])
submission2.head()

astro-ph  cond-mat   cs  eess  hep-ph  hep-th  math  q-bio  quant-ph  stat
0       0.0       0.0  0.0   0.0     0.0     0.0   0.0    0.0       0.0   1.0
1       0.0       0.0  0.0   0.0     1.0     0.0   0.0    0.0       0.0   0.0
2       0.0       0.0  0.0   1.0     0.0     0.0   0.0    0.0       0.0   0.0
3       0.0       0.0  0.0   0.0     0.0     0.0   0.0    1.0       0.0   0.0
4       0.0       1.0  0.0   0.0     0.0     0.0   0.0    0.0       0.0   0.0

In [ ]:
submission2 = submission2[['astro-ph','cond-mat','cs','eess','hep-ph','hep-th','math','q-bio','quant-ph','stat']].astype("uint8")

In [ ]:
result = pd.concat([test_df, submission2], axis=1)

In [ ]:
result.drop("category", axis = 1, inplace=True)

In [ ]:
result.head()

id  ... stat
0  2004.12573  ...    1
1  1908.01621  ...    0
2  1906.10356  ...    0
3  1905.10272  ...    0
4  1910.01033  ...    0

[5 rows x 13 columns]

In [ ]:
result.to_csv('result.csv', index = False)

In [ ]:
dummy_variable_2 = pd.get_dummies(test_df["category"])
test_df = pd.concat([test_df, dummy_variable_2], axis=1)
test_df.head()

id  ... stat
0  2004.12573  ...    0
1  1908.01621  ...    0
2  1906.10356  ...    0
3  1905.10272  ...    0
4  1910.01033  ...    0

[5 rows x 14 columns]

In [ ]:
compare = [(test_df['astro-ph'].isin(result['astro-ph'])),
           (test_df['cond-mat'].isin(result['cond-mat'])), 
           (test_df['cs'].isin(result['cs'])),
           (test_df['eess'].isin(result['eess'])),
           (test_df['hep-ph'].isin(result['hep-ph'])),
           (test_df['hep-th'].isin(result['hep-th'])),
           (test_df['math'].isin(result['math'])),
           (test_df['q-bio'].isin(result['q-bio'])),
           (test_df['quant-ph'].isin(result['quant-ph'])),
           (test_df['stat'].isin(result['stat']))]
print(type(compare))
compare = pd.DataFrame(compare)
compare = compare.T
compare.head

<class 'list'>


<bound method NDFrame.head of      astro-ph  cond-mat    cs  eess  ...  math  q-bio  quant-ph  stat
0        True      True  True  True  ...  True   True      True  True
1        True      True  True  True  ...  True   True      True  True
2        True      True  True  True  ...  True   True      True  True
3        True      True  True  True  ...  True   True      True  True
4        True      True  True  True  ...  True   True      True  True
..        ...       ...   ...   ...  ...   ...    ...       ...   ...
995      True      True  True  True  ...  True   True      True  True
996      True      True  True  True  ...  True   True      True  True
997      True      True  True  True  ...  True   True      True  True
998      True      True  True  True  ...  True   True      True  True
999      True      True  True  True  ...  True   True      True  True

[1000 rows x 10 columns]>

In [ ]:
compare.to_csv('compare.csv', index = False)